move code into commands/

diff --git a/theia b/theia
--- a/theia
+++ b/theia
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.2.12 (https://bashly.dev)
+# This script was generated by bashly 1.2.13 (https://bashly.dev)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -17,7 +17,12 @@ version_command() {
 
 # :command.usage
 theia_usage() {
-  printf "theia - Automatic recon\n\n"
+  if [[ -n $long_usage ]]; then
+    base64 -d <<<"H4sIADUnYWgA/4VN0Q2FQAj7Zwo2cCBz6QguwPDXFp4x0eQ1lUKpXMJIqkjM5MESJTuzqM2Dm2W31FNeGdonL7hnuZyBRiijlX/BujO+83tiKPt5R+1XZtZTOoN+DiI/okVVZOYvIjbgqoaBIQEAAA==" | gunzip
+
+  else
+    printf "theia - Automatic discovery of a given IP address\n\n"
+  fi
 
   printf "%s\n" "$(bold "Usage:")"
   printf "  theia COMMAND\n"
@@ -52,7 +57,7 @@ theia_init_usage() {
 
   printf "%s\n" "$(bold "Usage:")"
   printf "  theia init IPADDR [OPTIONS]\n"
-  printf "  theia init --help\n"
+  printf "  theia init --help | -h\n"
   echo
 
   # :command.long_usage
@@ -61,22 +66,13 @@ theia_init_usage() {
 
     # :command.usage_flags
     # :flag.usage
-    printf "  %s\n" "$(magenta "--name, -n NAME (required)")"
-    printf "    Name of target\n"
-    echo
-
-    # :flag.usage
-    printf "  %s\n" "$(magenta "--hostname, -h HOSTNAME")"
-    printf "    Hostname of target\n"
-    echo
-
-    # :flag.usage
-    printf "  %s\n" "$(magenta "--extension, -e EXTENSION")"
+    printf "  %s\n" "$(magenta "--extension, -e EXTENSION (required)")"
     printf "    URL extension of target\n"
+    printf "    %s\n" "Needs: --hostname"
     echo
 
     # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help")"
+    printf "  %s\n" "$(magenta "--help, -h")"
     printf "    Show this help\n"
     echo
 
@@ -91,7 +87,7 @@ theia_init_usage() {
     # :command.usage_examples
     printf "%s\n" "$(bold "Examples:")"
     printf "  theia init 127.0.0.1 --name anthem --hostname anthemvm --extension thm\n"
-    printf "  theia init 10.13.202.203\n"
+    printf "  theia init 10.13.202.203 -n lazarus\n"
     echo
 
   fi
@@ -103,7 +99,7 @@ theia_set_usage() {
 
   printf "%s\n" "$(bold "Usage:")"
   printf "  theia set IPADDR [OPTIONS]\n"
-  printf "  theia set --help\n"
+  printf "  theia set --help | -h\n"
   echo
 
   # :command.long_usage
@@ -112,22 +108,13 @@ theia_set_usage() {
 
     # :command.usage_flags
     # :flag.usage
-    printf "  %s\n" "$(magenta "--name, -n NAME (required)")"
-    printf "    Name of target\n"
-    echo
-
-    # :flag.usage
-    printf "  %s\n" "$(magenta "--hostname, -h HOSTNAME")"
-    printf "    Hostname of target\n"
-    echo
-
-    # :flag.usage
-    printf "  %s\n" "$(magenta "--extension, -e EXTENSION")"
+    printf "  %s\n" "$(magenta "--extension, -e EXTENSION (required)")"
     printf "    URL extension of target\n"
+    printf "    %s\n" "Needs: --hostname"
     echo
 
     # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help")"
+    printf "  %s\n" "$(magenta "--help, -h")"
     printf "    Show this help\n"
     echo
 
@@ -312,16 +299,20 @@ send_completions() {
   echo $'  local compline="${compwords[*]}"'
   echo $''
   echo $'  case "$compline" in'
+  echo $'    \'completions\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_theia_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
   echo $'    \'init\'*)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_theia_completions_filter "--extension --help --hostname -e -h")" -- "$cur")'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_theia_completions_filter "--extension --help -e -h")" -- "$cur")'
   echo $'      ;;'
   echo $''
   echo $'    \'set\'*)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_theia_completions_filter "--extension --help --hostname -e -h")" -- "$cur")'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_theia_completions_filter "--extension --help -e -h")" -- "$cur")'
   echo $'      ;;'
   echo $''
   echo $'    *)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_theia_completions_filter "--help --version -h -v init set")" -- "$cur")'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_theia_completions_filter "--help --version -h -v completions init set")" -- "$cur")'
   echo $'      ;;'
   echo $''
   echo $'  esac'
@@ -335,90 +326,32 @@ send_completions() {
 # :command.function
 theia_init_command() {
 
-  # src/init_command.sh
-  print_info() {
-    echo "$(blue [*])" "$1"
-  }
-
-  has_match() {
-    local pattern="$1"
-    local file="$2"
-
-    if  rg -q "$pattern" "$file" ; then
-      return 0
-    else
-      return 1
-    fi
-  }
-
-  name=${args[--name]}
-
-  print_info "creating $name/..."
-  mkdir $name
-
-  print_info "creating .env file"
-  # Create .env
-  cd $name
-  theia_set_command
-  cd ..
-
-  source $name/$name.env
-
-  print_info "starting nmap scan..."
-  nmap -sC -sV -T4 -p- $ip -oX $name/port-scan.xml -oN $name/port-scan.nmap
-
-  # enum web service shares
-  if has_match "http" $name/port-scan.nmap ; then
-    print_info "starting ffuf scan..."
-    ffuf -u $url/FUZZ -w /usr/share/seclists/Discovery/Web-Content/big.txt -recursion -recursion-depth 2 -t 100 -of md -o $name/web-dir.md
-    firefox $url
-  else
-    print_info "found no web port"
-  fi
-
-  # enum smb shares
-  if has_match "netbios-ssn" $name/port-scan.nmap ; then
-    print_info "startig enum4linux-ng scan..."
-    enum4linux-ng -As $ip -oJ smb-enum
-  else
-    print_info "found no smb ports"
-  fi
-
-  print_info "all scans complete."
-  print_info "add the following to /etc/hosts"
-  echo $ip $host.$ext
+  # src/commands/init.sh
+  echo "# This file is located at 'src/commands/init.sh'."
+  echo "# It contains the implementation for the 'theia init' command."
+  echo "# The code you write here will be wrapped by a function named 'theia_init_command()'."
+  echo "# Feel free to edit this file; your changes will persist when regenerating."
+  inspect_args
 
 }
 
 # :command.function
 theia_set_command() {
 
-  # src/set_command.sh
-  ip=${args[ipaddr]}
-  name=${args[--name]}
-  host=${args[--hostname]}
-  ext=${args[--extension]}
-  env_file="$name.env"
-
-  echo "# Created by Theia" >> $env_file
-
-  echo "ip=$ip" >> $env_file
-  if [ -z $host ] ; then
-    url="http://$ip"
-  else
-    url="http://$host.$ext"
-    echo "host=$host" >> $env_file
-  fi
-
-  echo "url=$url" >> $env_file
+  # src/commands/set.sh
+  echo "# This file is located at 'src/commands/set.sh'."
+  echo "# It contains the implementation for the 'theia set' command."
+  echo "# The code you write here will be wrapped by a function named 'theia_set_command()'."
+  echo "# Feel free to edit this file; your changes will persist when regenerating."
+  inspect_args
 
 }
 
 # :command.function
 theia_completions_command() {
 
-  # src/completions_command.sh
-  echo "# This file is located at 'src/completions_command.sh'."
+  # src/commands/completions.sh
+  echo "# This file is located at 'src/commands/completions.sh'."
   echo "# It contains the implementation for the 'theia completions' command."
   echo "# The code you write here will be wrapped by a function named 'theia_completions_command()'."
   echo "# Feel free to edit this file; your changes will persist when regenerating."
@@ -519,7 +452,7 @@ theia_init_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-      --help)
+      --help | -h)
         long_usage=yes
         theia_init_usage
         exit
@@ -532,6 +465,60 @@ theia_init_parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+  missing_deps=
+  # :dependency.filter
+  if ! command -v nmap >/dev/null 2>&1; then
+    printf "missing dependency: nmap\n" >&2
+    missing_deps=1
+  else
+    deps['nmap']="$(command -v nmap | head -n1)"
+  fi
+
+  # :dependency.filter
+  if ! command -v ffuf >/dev/null 2>&1; then
+    printf "missing dependency: ffuf\n" >&2
+    missing_deps=1
+  else
+    deps['ffuf']="$(command -v ffuf | head -n1)"
+  fi
+
+  # :dependency.filter
+  if ! command -v enum4linux-ng >/dev/null 2>&1; then
+    printf "missing dependency: enum4linux-ng\n" >&2
+    missing_deps=1
+  else
+    deps['enum4linux-ng']="$(command -v enum4linux-ng | head -n1)"
+  fi
+
+  # :dependency.filter
+  if ! command -v firefox >/dev/null 2>&1; then
+    printf "missing dependency: firefox\n" >&2
+    missing_deps=1
+  else
+    deps['firefox']="$(command -v firefox | head -n1)"
+  fi
+
+  # :dependency.filter
+  if ! command -v gunzip >/dev/null 2>&1; then
+    printf "missing dependency: gunzip\n" >&2
+    missing_deps=1
+  else
+    deps['gunzip']="$(command -v gunzip | head -n1)"
+  fi
+
+  # :dependency.filter
+  if ! command -v base64 >/dev/null 2>&1; then
+    printf "missing dependency: base64\n" >&2
+    missing_deps=1
+  else
+    deps['base64']="$(command -v base64 | head -n1)"
+  fi
+
+  if [[ -n $missing_deps ]]; then
+    exit 1
+  fi
+
   # :command.command_filter
   action="init"
 
@@ -539,34 +526,6 @@ theia_init_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-      # :flag.case
-      --name | -n)
-
-        # :flag.case_arg
-        if [[ -n ${2+x} ]]; then
-          args['--name']="$2"
-          shift
-          shift
-        else
-          printf "%s\n" "--name requires an argument: --name, -n NAME" >&2
-          exit 1
-        fi
-        ;;
-
-      # :flag.case
-      --hostname | -h)
-
-        # :flag.case_arg
-        if [[ -n ${2+x} ]]; then
-          args['--hostname']="$2"
-          shift
-          shift
-        else
-          printf "%s\n" "--hostname requires an argument: --hostname, -h HOSTNAME" >&2
-          exit 1
-        fi
-        ;;
-
       # :flag.case
       --extension | -e)
 
@@ -606,13 +565,24 @@ theia_init_parse_requirements() {
   # :command.required_args_filter
   if [[ -z ${args['ipaddr']+x} ]]; then
     printf "missing required argument: IPADDR\nusage: theia init IPADDR [OPTIONS]\n" >&2
+    # :command.examples_on_error
+    printf "examples:\n" >&2
+    printf "  theia init 127.0.0.1 --name anthem --hostname anthemvm --extension thm\n" >&2
+    printf "  theia init 10.13.202.203 -n lazarus\n" >&2
 
     exit 1
   fi
 
   # :command.required_flags_filter
-  if [[ -z ${args['--name']+x} ]]; then
-    printf "missing required flag: --name, -n NAME\n" >&2
+  if [[ -z ${args['--extension']+x} ]]; then
+    printf "missing required flag: --extension, -e EXTENSION\n" >&2
+    exit 1
+  fi
+
+  # :command.needy_flags_filter
+  # :flag.needs
+  if [[ -n ${args['--extension']+x} ]] && [[ -z "${args[--hostname]:-}" ]]; then
+    printf "%s\n" "--extension needs --hostname" >&2
     exit 1
   fi
 
@@ -624,7 +594,7 @@ theia_set_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-      --help)
+      --help | -h)
         long_usage=yes
         theia_set_usage
         exit
@@ -644,34 +614,6 @@ theia_set_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-      # :flag.case
-      --name | -n)
-
-        # :flag.case_arg
-        if [[ -n ${2+x} ]]; then
-          args['--name']="$2"
-          shift
-          shift
-        else
-          printf "%s\n" "--name requires an argument: --name, -n NAME" >&2
-          exit 1
-        fi
-        ;;
-
-      # :flag.case
-      --hostname | -h)
-
-        # :flag.case_arg
-        if [[ -n ${2+x} ]]; then
-          args['--hostname']="$2"
-          shift
-          shift
-        else
-          printf "%s\n" "--hostname requires an argument: --hostname, -h HOSTNAME" >&2
-          exit 1
-        fi
-        ;;
-
       # :flag.case
       --extension | -e)
 
@@ -716,8 +658,15 @@ theia_set_parse_requirements() {
   fi
 
   # :command.required_flags_filter
-  if [[ -z ${args['--name']+x} ]]; then
-    printf "missing required flag: --name, -n NAME\n" >&2
+  if [[ -z ${args['--extension']+x} ]]; then
+    printf "missing required flag: --extension, -e EXTENSION\n" >&2
+    exit 1
+  fi
+
+  # :command.needy_flags_filter
+  # :flag.needs
+  if [[ -n ${args['--extension']+x} ]] && [[ -z "${args[--hostname]:-}" ]]; then
+    printf "%s\n" "--extension needs --hostname" >&2
     exit 1
   fi
 
