add docs

diff --git a/theia b/theia
--- a/theia
+++ b/theia
@@ -57,7 +57,7 @@ theia_init_usage() {
 
   printf "%s\n" "$(bold "Usage:")"
   printf "  theia init IPADDR [OPTIONS]\n"
-  printf "  theia init --help | -h\n"
+  printf "  theia init --help\n"
   echo
 
   # :command.long_usage
@@ -66,13 +66,24 @@ theia_init_usage() {
 
     # :command.usage_flags
     # :flag.usage
-    printf "  %s\n" "$(magenta "--extension, -e EXTENSION (required)")"
+    printf "  %s\n" "$(magenta "--name, -n NAME (required)")"
+    printf "    Name of target\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--hostname, -h HOSTNAME")"
+    printf "    Hostname of target\n"
+    printf "    %s\n" "Needs: --extension"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--extension, -e EXTENSION")"
     printf "    URL extension of target\n"
     printf "    %s\n" "Needs: --hostname"
     echo
 
     # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "  %s\n" "$(magenta "--help")"
     printf "    Show this help\n"
     echo
 
@@ -99,7 +110,7 @@ theia_set_usage() {
 
   printf "%s\n" "$(bold "Usage:")"
   printf "  theia set IPADDR [OPTIONS]\n"
-  printf "  theia set --help | -h\n"
+  printf "  theia set --help\n"
   echo
 
   # :command.long_usage
@@ -108,13 +119,24 @@ theia_set_usage() {
 
     # :command.usage_flags
     # :flag.usage
-    printf "  %s\n" "$(magenta "--extension, -e EXTENSION (required)")"
+    printf "  %s\n" "$(magenta "--name, -n NAME (required)")"
+    printf "    Name of target\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--hostname, -h HOSTNAME")"
+    printf "    Hostname of target\n"
+    printf "    %s\n" "Needs: --extension"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "$(magenta "--extension, -e EXTENSION")"
     printf "    URL extension of target\n"
     printf "    %s\n" "Needs: --hostname"
     echo
 
     # :command.usage_fixed_flags
-    printf "  %s\n" "$(magenta "--help, -h")"
+    printf "  %s\n" "$(magenta "--help")"
     printf "    Show this help\n"
     echo
 
@@ -321,11 +343,11 @@ send_completions() {
   echo $'      ;;'
   echo $''
   echo $'    \'init\'*)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_theia_completions_filter "--extension --help -e -h")" -- "$cur")'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_theia_completions_filter "--extension --help --hostname --name -e -h -n")" -- "$cur")'
   echo $'      ;;'
   echo $''
   echo $'    \'set\'*)'
-  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_theia_completions_filter "--extension --help -e -h")" -- "$cur")'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_theia_completions_filter "--extension --help --hostname --name -e -h -n")" -- "$cur")'
   echo $'      ;;'
   echo $''
   echo $'    *)'
@@ -555,7 +577,7 @@ theia_init_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-      --help | -h)
+      --help)
         long_usage=yes
         theia_init_usage
         exit
@@ -606,6 +628,34 @@ theia_init_parse_requirements() {
     key="$1"
     case "$key" in
       # :flag.case
+      --name | -n)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--name']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--name requires an argument: --name, -n NAME" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --hostname | -h)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--hostname']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--hostname requires an argument: --hostname, -h HOSTNAME" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
       --extension | -e)
 
         # :flag.case_arg
@@ -653,12 +703,18 @@ theia_init_parse_requirements() {
   fi
 
   # :command.required_flags_filter
-  if [[ -z ${args['--extension']+x} ]]; then
-    printf "missing required flag: --extension, -e EXTENSION\n" >&2
+  if [[ -z ${args['--name']+x} ]]; then
+    printf "missing required flag: --name, -n NAME\n" >&2
     exit 1
   fi
 
   # :command.needy_flags_filter
+  # :flag.needs
+  if [[ -n ${args['--hostname']+x} ]] && [[ -z "${args[--extension]:-}" ]]; then
+    printf "%s\n" "--hostname needs --extension" >&2
+    exit 1
+  fi
+
   # :flag.needs
   if [[ -n ${args['--extension']+x} ]] && [[ -z "${args[--hostname]:-}" ]]; then
     printf "%s\n" "--extension needs --hostname" >&2
@@ -673,7 +729,7 @@ theia_set_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-      --help | -h)
+      --help)
         long_usage=yes
         theia_set_usage
         exit
@@ -693,6 +749,34 @@ theia_set_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
+      # :flag.case
+      --name | -n)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--name']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--name requires an argument: --name, -n NAME" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --hostname | -h)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--hostname']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--hostname requires an argument: --hostname, -h HOSTNAME" >&2
+          exit 1
+        fi
+        ;;
+
       # :flag.case
       --extension | -e)
 
@@ -737,12 +821,18 @@ theia_set_parse_requirements() {
   fi
 
   # :command.required_flags_filter
-  if [[ -z ${args['--extension']+x} ]]; then
-    printf "missing required flag: --extension, -e EXTENSION\n" >&2
+  if [[ -z ${args['--name']+x} ]]; then
+    printf "missing required flag: --name, -n NAME\n" >&2
     exit 1
   fi
 
   # :command.needy_flags_filter
+  # :flag.needs
+  if [[ -n ${args['--hostname']+x} ]] && [[ -z "${args[--extension]:-}" ]]; then
+    printf "%s\n" "--hostname needs --extension" >&2
+    exit 1
+  fi
+
   # :flag.needs
   if [[ -n ${args['--extension']+x} ]] && [[ -z "${args[--hostname]:-}" ]]; then
     printf "%s\n" "--extension needs --hostname" >&2
